### ISSUE TITLE
Error Indexing

### ISSUE THREAD

**Issue by hiramustafa77** [pxq0312/SFANet-crowd-counting#4]
I am getting this error , I am unable to figure out the issue

Traceback (most recent call last):
  File "train.py", line 57, in <module>
    for i, (images, density, att) in enumerate(train_loader):
  File "/home/hiramustafa/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/hiramustafa/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/hiramustafa/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hiramustafa/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hiramustafa/Downloads/Thesis_new/dataset.py", line 32, in __getitem__
    label = h5py.File(self.label_list[index], 'r')
IndexError: list index out of range

**Comment by hiramustafa77** [comment]
Figured it out first we need to create the density maps those are used/called in the train file
